platform:
  - x64
environment:
  global:
    MSYS2_BASEVER: 20150512
  matrix:
    - MSYS2_ARCH: i686
      MSYS2_BITS: 32
      MSYSTEM: MINGW32
    - MSYS2_ARCH: x86_64
      MSYS2_BITS: 64
      MSYSTEM: MINGW64
install:
  - ps: If (Test-Path ("msys" + $env:MSYS2_BITS)){Write-Host "Using cached msys2"}
  - ps: If (!(Test-Path ("msys" + $env:MSYS2_BITS))){Invoke-WebRequest -UserAgent wget -Uri ("http://kent.dl.sourceforge.net/project/msys2/Base/" + $env:MSYS2_ARCH +  "/msys2-base-" + $env:MSYS2_ARCH + "-" + $env:MSYS2_BASEVER + ".tar.xz") -OutFile "msys2.tar.xz"}
  - ps: If (!(Test-Path ("msys" + $env:MSYS2_BITS))){&"7z" x msys2.tar.xz}
  - ps: If (!(Test-Path ("msys" + $env:MSYS2_BITS))){&"7z" x msys2.tar > $nul;&("msys" + $env:MSYS2_BITS + "\usr\bin\bash") -lc "";&("msys" + $env:MSYS2_BITS + "\usr\bin\bash") -lc ("for i in {1..3}; do pacman --noconfirm -Suy autoconf automake pkg-config mingw-w64-i686-gcc mingw-w64-x86_64-gcc make zlib-devel && break || sleep 15; done");&("msys" + $env:MSYS2_BITS + "\autorebase.bat");}

build_script:
  - msys%MSYS2_BITS%\usr\bin\bash -lc "mkdir /tmp;cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; ./bootstrap; ./configure; make"
  - cd %APPVEYOR_BUILD_FOLDER%
  - move src roswell
  - 7z a Roswell-%MSYS2_ARCH%.zip roswell/ros.exe roswell/lisp/*.*

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\roswell
  - ros version
  - ros setup
  - ros version=t run
  - ros config
  - ros install sbcl
  - ros config
  - ros -s prove-asdf -s quri-test -e "(asdf:test-system :quri-test)"

artifacts:
  - path: Roswell-x86_64.zip
    name: Roswell-x86_64.zip
  - path: Roswell-i686.zip
    name: Roswell-i686.zip

cache:
  - msys64
# - msys64 -> .appveyor.yml
  - msys32
# - msys32 -> .appveyor.yml
