language: common-lisp

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; brew update
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; brew --env
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; brew config
install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; brew tap snmsts/roswell

script:
  - find . \( -name \*.c -o -name \*.h \) -type f|xargs wc -l -c
  - find . \( -name \*.go \) -type f|xargs wc -l -c
  - find . \( -name \*.lisp -o -name \*.ros \) -type f|xargs wc -l -c
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; brew install roswell --verbose --HEAD
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; sh bootstrap
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; ./configure
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; make -j4
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; sudo make install
  - ros version
  - ros -v setup
  - ros list
  - ros -v run -- --version
  - ros install sbcl
  - ros -v run -- --version
  - ros install ccl-bin
  - ros -v run -- --version
  - ros config
  - man -Pcat ros
