language: c

compiler:
  - gcc
  - clang

script:
  - find . \( -name \*.c -o -name \*.h -o -name \*.lisp -o -name \*.ros \) -type f|xargs wc -l
  - sh bootstrap
  - ./configure
  - make -j4
  - sudo make install
  - ros version
  - ros -v setup
  - ros -v run -- --version
  - ros install ccl-bin
  - ros -v run -- --version
  - ros config
  - man -Pcat ros
  - make test
