language: common-lisp
sudo: required
env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=master
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - BREW= LISP=alisp
    - BREW= LISP=abcl
    - BREW=true
    - BREW= LISP=sbcl
    - BREW= LISP=ccl-bin
    - BREW= LISP=clisp
    - BREW= LISP=cmucl
    - BREW= LISP=ecl
os:
  - linux
  - osx
matrix:
  exclude:
  - os: linux
      BREW: true
  
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew --env; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew config; fi
install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$BREW" = "true" ]; then brew tap snmsts/roswell; fi

script:
  - if [ "$BREW" = "true" ]; then find . \( -name \*.c -o -name \*.h \) -type f|xargs wc -l -c; fi
  - if [ "$BREW" = "true" ]; then find . \( -name \*.go \) -type f|xargs wc -l -c; fi
  - if [ "$BREW" = "true" ]; then find . \( -name \*.lisp -o -name \*.ros \) -type f|xargs wc -l -c; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$BREW" = "true" ]; then brew install roswell --verbose --HEAD; fi
  - if [ "$BREW" != "true" ]; then sh ./scripts/install-for-ci.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] || [ "$BREW" != "true" ]; then ros version; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] || [ "$BREW" != "true" ]; then ros -v version=t run; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] || [ "$BREW" != "true" ]; then ros config; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] || [ "$BREW" != "true" ]; then ros -s prove-asdf -s quri-test -e "(asdf:test-system :quri-test)"; fi
