language: c
sudo: false
dist: xenial
env:
  global:
    - PATH=~/.roswell/bin:/home/linuxbrew/.linuxbrew/bin:$PATH
    - ROSWELL_BRANCH=$TRAVIS_BRANCH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - ROSWELL_REPO=https://github.com/${TRAVIS_REPO_SLUG}
  matrix:
    - METHOD=ci LISP=alisp
    - METHOD=ci LISP=cmu-bin/2019-06
    - METHOD=ci LISP=sbcl
    - METHOD=ci LISP=ecl
    - METHOD=ci LISP=mkcl
    - METHOD=ci LISP=clisp
    - METHOD=ci LISP=abcl
    - METHOD=ci LISP=ccl-bin
    - METHOD=brew
    - METHOD=ci LISP=sbcl/1.1.14
    - METHOD=ci LISP=ccl32
    - METHOD=ci LISP=sbcl/git

os:
  - osx
  - linux

matrix:
  allow_failures:
    - env: METHOD=brew
    - env: METHOD=ci LISP=sbcl/git
    - env: METHOD=ci LISP=mkcl
    - env: METHOD=ci LISP=abcl
  include:
      - sudo: required
        os: linux
        env: METHOD=valgrind XCFLAGS="-g -O0"
        addons:
          apt:
            packages:
              - valgrind
      - os: linux
        env: METHOD=documents
        addons:
          apt:
            packages:
              - pandoc
              - ruby-sass
      - os: windows
        env: METHOD=ci LISP=sbcl-bin
      - os: linux
        arch: arm64
        env: METHOD=ci LISP=sbcl-bin
        addons:
          apt:
            packages:
              - libcurl4-openssl-dev

#branches:
#  except:
#      - /^v[0-9]/

addons:
  apt:
    packages:
      - libc6-i386
#      - gcc-multilib


before_install:
  - date
  - if [ $METHOD = documents ]; then
       find . \( -name \*.lisp -o -name \*.ros \) -type f|xargs wc -l -c;
       find . \( -name \*.c -o -name \*.h \) -type f|xargs wc -l -c;
       pandoc -v;
    fi
  - if [ $METHOD = brew ] && [ $TRAVIS_OS_NAME = linux ]; then
       yes ""| sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"; fi
  - if [ $METHOD = brew ] || [ $TRAVIS_OS_NAME = osx ]; then brew update;brew --env;brew config; fi
  - if [ $METHOD = brew ]; then brew doctor || true; fi

install:
  - if [ $METHOD = brew ] && [ $TRAVIS_OS_NAME = linux ]; then brew install curl; fi
  - if [ $METHOD = brew ]; then brew install roswell --HEAD; fi
  - if [ "$METHOD" = "valgrind" ]; then
       sh bootstrap;
       CFLAGS=$XCFLAGS ./configure --disable-dependency-tracking --disable-maintainer-mode;
       make;
       sudo make install;
       make maintainer-clean;
    fi
  - if [ "$METHOD" = "ci" ]; then sh ./scripts/install-for-ci.sh; fi

script:
  - if [ "$METHOD" = "documents" ]; then
      rm documents/man/* documents/html/*;
      sh bootstrap;
      ./configure --enable-manual-generation --enable-html-generation;
      make;
      sudo make install;
    fi
  - if [ "$METHOD" = "valgrind" ]; then
       ros setup;
       valgrind --leak-check=yes ros config;
    fi
  - if [ "$METHOD" = "brew" ] || [ "$METHOD" = "ci" ]; then
       ros version;
       ros version=t run;
       ros install prove;
       run-prove roswell-test.asd 2>&1;
    fi
  - if [ "$METHOD" = "ci" ]; then
       ros -q run && [`ros -q run 2>&1` == ""];
    fi
  - if [ "$LISP" = "sbcl-bin" ] && [ x$ALLOW_FAILURES != x ]; then
       if [ $TRAVIS_OS_NAME = osx ]; then
          sudo ros -e '(ignore-errors (with-open-file (o (format nil "/~A" (code-char 12354)) :direction :output)))';
       fi;
       if [ $ALLOW_FAILURES = YES ]; then
         ros sbcl.patchless=t install sbcl;
       else
         ros install sbcl --sbcl-bin;
         [`ros -e "(ros:ignore-shebang)" -e '(loop for x in (directory "src/lisp/*.ros") do (load x))' 2>&1` == ""];
       fi;
       make -C t/tree-shaker ;
    fi
  - ros config

after_success:
  - git config user.email "auto@example.com"; git config user.name "Travis-CI";
  - if [ "$METHOD" = "documents" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
       git branch;git status;
       git checkout $TRAVIS_BRANCH;git add -u;git add documents/man/* documents/html/*;
       git commit -m "[ci skip] documents update";
       git push --force --quiet "https://${GITHUB_OAUTH_TOKEN}:x-oauth-basic@github.com/roswell/roswell.git" $TRAVIS_BRANCH > /dev/null 2>&1;
    fi
